### ISSUE TITLE
Request - Repeat Mode

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TeamFelnull/IamMusicPlayer#1]
I am still dabbling in the mod but I didn't notice a repeat mode. Any plans to add one? Also could we get modern stereo models and other types of stereos? Otherwise 100% fantastic.

**Comment by MG8853** [comment]
Repeat mode can be activated by continuing to send the redstone signal.

**Comment by P3rf3ctXZer0** [comment]
Would that be tick consuming?
