### ISSUE TITLE
[1.16.5] Suggestion

### ISSUE THREAD

**Issue by FrannDzs** [TeamFelnull/IamMusicPlayer#15]
Hi guys, how are you? I hope you are doing well. I'm the one who translated this mod to spanish, and I came up with an idea, to add support for the https protocol, to be able to play online radio streams like:
https://cdn.instream.audio/:9202/stream
What do you think about this idea? For me it would be great guys, a last update to 1.16. Greetings and good night :3

**Comment by MORIMORI0317** [comment]
Thank you for a very good idea.
However, we are currently rewriting almost everything in 1.17 and it is difficult to develop 1.16.5 at the same time, it may be possible to implement that function in 1.17.
