### ISSUE TITLE
1.18.1 crash on startup

### ISSUE THREAD

**Issue by ZEROX7** [TeamFelnull/IamMusicPlayer#19]
it crashes with launcher error code 1 it doesnt give me a crash log or writes any thing in to the latest log
forge 37.0.79

**Comment by MORIMORI0317** [comment]
Please tell me the MOD list and each version when it crashed

**Comment by ZEROX7** [comment]
i made it easy for you XD
https://www.curseforge.com/minecraft/modpacks/singularity-create
and add your mod to it

**Comment by MORIMORI0317** [comment]
Seems to have been in conflict with Lightman's Discord Integration
Released a fixed version
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3670578
