### ISSUE TITLE
Serverside Crash - When obtaining song.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TeamFelnull/IamMusicPlayer#2]
Full report and potential offending code.
https://gist.github.com/P3rf3ctXZer0/15f9c3ade499b0c1dd0053515b0bc72f

**Comment by P3rf3ctXZer0** [comment]
[08Jun2020 22:53:11.827] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
	at net.morimori.imp.file.PlayList.getWorldPlaylistNBTDataString(PlayList.java:181) ~[?:1.1]
	at net.morimori.imp.tileentity.CassetteDeckTileEntity.finishRecoding(CassetteDeckTileEntity.java:80) ~[?:1.1]
	at net.morimori.imp.tileentity.CassetteDeckTileEntity.func_73660_a(CassetteDeckTileEntity.java:170) ~[?:1.1]
	at net.minecraft.world.World.func_217391_K(World.java:1407) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?]
	... 4 more

**Comment by MG8853** [comment]
Would you please send the music file with the error?

**Comment by MORIMORI0317** [comment]
Plase send "worldfolder/iammusicolayer/play.dat".

**Comment by nin8995** [comment]
Could you send a file at saves/*worldname*/iammusicplayer/playlist.dat?

**Comment by nin8995** [comment]
Could you send a NBT file at world/iammusicplayer/playlist.dat?

**Comment by nin8995** [comment]
Would you send a NBT file at world/iammusicplayer/playlist.dat?

**Comment by P3rf3ctXZer0** [comment]
How would I do that?

**Comment by P3rf3ctXZer0** [comment]
Even more raw version (Had to zip it though github policy)
[#NL - Sonic Unleashed - Apotos [Windmill Isle Day].zip](https://github.com/TeamFelnull/IamMusicPlayer/files/4752399/NL.-.Sonic.Unleashed.-.Apotos.Windmill.Isle.Day.zip)

**Comment by P3rf3ctXZer0** [comment]
Not sure if this helps but I just copied the whole "iammusicplayer" folder and its contents to server after using it in single player.

**Comment by P3rf3ctXZer0** [comment]
Strange playlist.dat does not exist.

**Comment by P3rf3ctXZer0** [comment]
[playlist.zip](https://github.com/TeamFelnull/IamMusicPlayer/files/4752609/playlist.zip)

**Comment by P3rf3ctXZer0** [comment]
![image](https://user-images.githubusercontent.com/10351221/84158795-e3c9e400-aa31-11ea-9e5b-3b54908872d3.png)

I think its a ticking entity bug. NBT looks fine.

**Comment by P3rf3ctXZer0** [comment]
Another nbt image from a different nbt reader 
![image](https://user-images.githubusercontent.com/10351221/84159248-7a96a080-aa32-11ea-9e86-9bf274a8665a.png)

**Comment by MORIMORI0317** [comment]
Could not pinpoint the cause.
Please delete "playlist.dat" and execute "/worldplaylistreload".
If that doesn't work please let us know.

**Comment by P3rf3ctXZer0** [comment]
I already did that twice.

**Comment by P3rf3ctXZer0** [comment]
https://www.youtube.com/watch?v=q94DLFbW8Dg

**Comment by P3rf3ctXZer0** [comment]
I am trying to find you some help from very skilled contacts. I will let you know what I discover.

**Comment by P3rf3ctXZer0** [comment]
https://www.minecraftforge.net/forum/forum/70-modder-support/

**Comment by MG8853** [comment]
No Error
https://youtu.be/wAxO7T9ZcLk

If you don't mind, can you tell me the OS and specifications that the Minecraft server is running?

We have a test environment only on Windows, so we can not handle it if the error is on another OS.

**Comment by P3rf3ctXZer0** [comment]
Windows 10

**Comment by P3rf3ctXZer0** [comment]
The video shows the crash and how I got there even shows my server folder.

**Comment by MORIMORI0317** [comment]
I understood the cause, so I will fix it in the next version

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/2982273
Released a fixed  new version.

**Comment by P3rf3ctXZer0** [comment]
My issue is on windows not mac or linux will your fix still work?

**Comment by MORIMORI0317** [comment]
maybe OK.
If not, please report it

**Comment by P3rf3ctXZer0** [comment]
Alright leave this open I will be testing shortly.

**Comment by P3rf3ctXZer0** [comment]
Seems to work fine now :D
