### ISSUE TITLE
3.13 will not load

### ISSUE THREAD

**Issue by ipiiia** [TeamFelnull/IamMusicPlayer#28]
No logs were found to cause the error.
3.12 loads normally and works fine.

java17 or 18
m1 Mac
1.18.2
fabric

architectury 4.4.68

**Comment by MORIMORI0317** [comment]
I checked the operation in the same environment, but it played normally and no problem was confirmed.
If it's a music load, 3.12 to 3.13 only changes the integration with emojiful, and there may be other causes.
Please restart Minecraft and check the network status.
If Minecraft fails to start, please tell me the list of mods you are using (or modpack name)

**Comment by ipiiia** [comment]
> I checked the operation in the same environment, but it played normally and no problem was confirmed.
> If it's a music load, 3.12 to 3.13 only changes the integration with emojiful, and there may be other causes.
> Please restart Minecraft and check the network status.
> If Minecraft fails to start, please tell me the list of mods you are using (or modpack name)

no special log and no crash,, I don't have any other mods,,strange
It just doesn't show up in the inventory (Not loaded to game

**Comment by MORIMORI0317** [comment]
Please tell me the name of the MOD jar file

**Comment by ipiiia** [comment]
Oh I downloaded the all of mods file manually and the problem was solved.
I think there was a problem with the jar file that was updated by the mod updater 🙇
