### ISSUE TITLE
not combitable with newest forge

### ISSUE THREAD

**Issue by ZEROX7** [TeamFelnull/IamMusicPlayer#3]
forge version 106
error
Failed to register automatic subscribers. ModID: iammusicplayer, class red.felnull.imp.IamMusicPlayer
java.lang.IllegalArgumentException: Method public static void red.felnull.imp.client.handler.RenderHandler.onRender(net.minecraftforge.event.TickEvent$RenderTickEvent) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.event.TickEvent$RenderTickEvent

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3024964
Released a new fixed version.
