### ISSUE TITLE
crashes on load up [1.16.1]

### ISSUE THREAD

**Issue by SDUBZ** [TeamFelnull/IamMusicPlayer#4]
Forge: 1.16.1-32.0.106

IamMusicPlayer-1.16.1-1.3

logs:
[latest.log](https://github.com/TeamFelnull/IamMusicPlayer/files/5035461/latest.log)

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3024964
Try the latest version
