### ISSUE TITLE
[Suggestion] Sound distance + portable boombox

### ISSUE THREAD

**Issue by Riushda** [TeamFelnull/IamMusicPlayer#5]
I was wondering if it wouldn't be too hard to make it possible that when you get away from the boombox the sound decreases and when you get closer it increases. And additional cool feature would be the possibility to play music when the boombox is in the hand of the player or you could create a new slot (like a backpack slot) to make it possible for the player to put the boombox on his shoulder.
For information, I'm a computer science student and I have already developed in java  so if you want help I would gladly help you.

**Comment by MORIMORI0317** [comment]
Currently, it has been ported to 1.16.3 and recreated on a large scale. I don't know when it will be, but the next update will implement a portable boombox.

**Comment by Riushda** [comment]
sorry I didn't realize that the first feature that i proposed was already implemented, this mod is awesome !
