### ISSUE TITLE
FFmpeg Error

### ISSUE THREAD

**Issue by Patrick1417** [TeamFelnull/IamMusicPlayer#6]
Hi,
i installed your newest version IamMusicPlayer-1.16.3-2.0.jar on our forge 1.16.4 Server.

If i try to playback a youtube music downloaded to my cassette i always get an FFmpeg error, it starts reloading the FFmpeg but it doesn't work. 
And if i try to upload a file from my computer, it always tells me "no support format", i tried a lot of formats but non of it is working.

Tried to download a different FFmpeg version but its not working either.

![2021-01-16_00 58 51](https://user-images.githubusercontent.com/65871539/104789692-0b3a1980-5796-11eb-9926-6a9a2f61f327.png)

**Comment by MORIMORI0317** [comment]
Try deleting the IamMusicPlayer folder in the directory.
The next version will add the ability to export detailed FFmpeg errors as a report.
If deleting the IamMusicPlayer folder does not help, try the next version.

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3170050

**Comment by Patrick1417** [comment]
Just tried deleting the IamMusicPlayer folder and downloaded the new mod version, still doesn't work.

**Comment by MORIMORI0317** [comment]
If an error occurs in the new version, a report will be generated in ffmpeg-reports in IamMusicPlayer in the directory.
Please give me that report file

**Comment by Patrick1417** [comment]
[error-2021-47-16_13.47.27.txt](https://github.com/TeamFelnull/IamMusicPlayer/files/5824418/error-2021-47-16_13.47.27.txt)

**Comment by MORIMORI0317** [comment]
Thank you, parse this and fix the error

**Comment by MORIMORI0317** [comment]
Thanks, I parse this and fix the error

**Comment by Patrick1417** [comment]
Thank you very much.

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3171153
I was able to identify the cause, so I fixed it.
Maybe fix the FFmpeg error

**Comment by Patrick1417** [comment]
Awesome. 
It's now working without a problem.
Good job!
