### ISSUE TITLE
Request: Don't redownload ffmpeg every load

### ISSUE THREAD

**Issue by TechniumUnlimited** [TeamFelnull/IamMusicPlayer#7]
It would be far wiser to check if ffmpeg is already downloaded and use it if so instead of downloading it every time you load the game

**Comment by MORIMORI0317** [comment]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3171153
Should have been fixed in the new version

**Comment by bence1971387** [comment]
It redownloads for me if i restart the game.
I get the following lines every time i try to play a song on the boombox and it redownloads FFMPEG. i cannot start any song.
the boombox just says "Loading"

FFMPEG Error
Get Info Error
Reload FFMPEG

**Comment by MG8853** [comment]
New Release
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer/files/3487094
